# Generated by Django 4.2.20 on 2025-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
