# Generated by Django 4.2.20 on 2025-05-07 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_servicecategory_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecategory",
            name="featured",
        ),
    ]
