# Generated by Django 4.2.20 on 2025-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_remove_servicecategory_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
