# Generated by Django 4.2.20 on 2025-05-19 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="List of key features",
                null=True,
                size=None,
            ),
        ),
    ]
