# Generated by Django 4.2.20 on 2025-05-19 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_service_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="List of key features",
                size=None,
            ),
        ),
    ]
