# Generated by Django 4.2.20 on 2025-06-03 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_service_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.DeleteModel(
            name="ServiceCategory",
        ),
    ]
